name: 🥚 template/image Request
description: Suggest a server to build an template/image for
title: "[Request]: <Software/Game>"
labels: ["template/image request"]
body:
  - type: markdown
    attributes:
      value: |
          Make sure there are no existing template/image requests by searching the [repository issues](https://github.com/gOOvER/moonlight-templates/labels/template%20request). Please understand how Moonlight Panel works when you are requesting an template/image. (ie. docker-compose doesn't work for a moonlight server)
  - type: dropdown
    id: expand
    attributes:
      label: Does this expand an already existing service
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: expand
    attributes:
      label: Would you donate for the creation? 
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: expand
    attributes:
      label: Would you donate the game/gamekey? 
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: game-link
    attributes:
      label: Link to a game or software
      placeholder: minecraft.net/factorio.com/etc
    validations:
      required: true
  - type: input
    id: download-link
    attributes:
      label: Links for the download
      description: This needs to be an official link and not one that is hosted on some forum page or a personal Github page. Docker image is not a viable option.
    validations:
      required: true
  - type: input
    id: instruction-link
    attributes:
      label: Links for the install docs
      description: Link to installation instructions or documentation covering required dependencies and configuration for the server creation. Docker image is not installation documentation!
    validations:
      required: true
